Profile and news
frontend-park-mail-ru/2021_1_Swerter pull request #6
Opened 2021-03-06 21:00 UTC by Burunduck

2021-03-06 21:36 UTC, zelflod reviewed
✊

2021-03-06 21:36 UTC, zelflod commented on README.md
> +**MyMotivation** — это соцсеть. Социальная сеть. Друзья, чаты, новости и группы - это всё про нас.
не понял, что это?) какая сеть?)

2021-03-06 21:36 UTC, zelflod commented on package.json
> +  "description": "## Описание",
давай напишем name и description

2021-03-06 21:36 UTC, zelflod commented on public/components/header/header.js
> +function header(locals) {var pug_html = "", pug_mixins = {}, pug_interp;pug_html = pug_html + "\u003C!--style--\u003E\u003C!--    include header.css--\u003E\u003Cdiv class=\"header\"\u003E\u003Cdiv c
это сгенерированный файл? он точно нужен?

2021-03-06 21:36 UTC, zelflod commented on public/components/header/header.pug
> +//    include header.css
не нужные комменты лучше убрать

2021-03-06 21:36 UTC, zelflod commented on public/components/post/post.css
> +.avatar-in-post{
Знакомы с БЭМ? Давайте использовать методологию БЭМ. Там очень просто https://ru.bem.info/methodology/quick-start/

2021-03-06 21:36 UTC, zelflod commented on public/components/header/header.js
> +function header(locals) {var pug_html = "", pug_mixins = {}, pug_interp;pug_html = pug_html + "\u003C!--style--\u003E\u003C!--    include header.css--\u003E\u003Cdiv class=\"header\"\u003E\u003Cdiv c
такие файлы обычно не попадают в репозиторий

2021-03-13 21:13 UTC, zelflod requested changes

2021-03-13 21:13 UTC, zelflod commented on public/components/AddPost/handler.js
> +(function() {
Вам точно нужен IIFE во всех js файлах? Если не хотите глобал скоуп засорять и использовать импорты/экспорты, то используйте es modules, просто пишите `<script type="module" src="...">`

2021-03-13 21:13 UTC, zelflod commented on public/components/AddPost/handler.js
> +    addBackendPost();
вначале добавьте пост в бэк и в случае успеха покажите добавленный пост, потому что сетевой запрос может сфэйлиться, и получитя что вы обманите юзера

```
http.post({url: '/posts/add', data: formData, headers: {}}).then(() => {
    addFrontendPost();
})
```

2021-03-13 21:13 UTC, zelflod commented on public/components/AddPost/handler.js
> +(function() {
потом вместо 
```
window.addPost = addPost;
```

будете писать 
```
export function addPost() {};
```

а в других файлах импортить 

```
import {addPost} from ./path/to/module 
```

2021-03-13 21:13 UTC, zelflod commented on public/components/Header/handler.js
> +    console.log(user);
консол логи в мастер нельзя пушать

2021-03-13 21:13 UTC, zelflod commented on public/components/RegisterForm/handler.js
> +    console.log('Register');
убрать) везде)

2021-03-13 21:13 UTC, zelflod commented on public/index.html
> +<script src="main.js"></script>
подумайте над использованием type="module"

2021-03-13 21:13 UTC, zelflod commented on public/modules/http.js
> +            console.log(response)
убрать

2021-03-13 21:13 UTC, zelflod commented on public/modules/http.js
> +        async #fetchUnsafe({url = '', data = JSON.stringify({}), headers = {
чем #fetchSafe отличается от #fetchUnsafe? не вижу смысла в разделении в две функции

2021-03-20 09:49 UTC, zelflod requested changes
обратите внимание на все комменты

2021-03-20 09:49 UTC, zelflod commented on public/index.html
> +<script type="module" src="components/RegisterForm/handler.js"></script>
Не вижу смысла явно приписывать их здесь, достаточно только 
```
<script async type="module" src="main.js"></script>
```
который в свою очередь использует дгугие модули и они сами загрузятся брузером

https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Modules

2021-03-20 09:49 UTC, zelflod commented on public/main.js
> +'use strict';
когда используете type="module", то 'use strict' будет по умолчанию, не надо явно приписывать

ref https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Modules

2021-03-20 10:30 UTC, zelflod commented on public/components/AddPost/handler.js
> +    addBackendPost();
сделать потом

2021-04-01 18:20 UTC, PiroDev commented on public/index.html
> +<script type="module" src="components/RegisterForm/handler.js"></script>
Исправили

2021-04-01 18:37 UTC, PiroDev commented on public/modules/http.js
> +        async #fetchUnsafe({url = '', data = JSON.stringify({}), headers = {
Отличие в том, что для fetchSafe выделен специально для "безопасных" методов, а fetchUnsafe - для "небезобасных". Разделение позволяет устанавливать различную samesite cookies политику для разных запросов.

2021-04-02 17:44 UTC, zelflod approved these changes

2021-04-02 17:45 UTC, merged